---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-oms
  namespace: hello-svc
spec:
  encryptedData:
    DATABASE_URL: AgB/5E4HupvzFdAO59kXbE2LELbyiLVbTw27vTLAmB8HNvSnVTEHtXxT+FmvWFzfgbDsrlGf0wIJwRm1Cwt7A+5e+0kBBWsUICvk8BqHkwhcf1WlE7XANYWCvGKN+zBwUTOxTQ9SA/0scbOdj/GiNHU+39PmFGFybIkDfUDTml1hpAB1QcTus4Me5WAYlW8+KDiFgnRJ0Aw7K/jGNPWEqNK59ScDQ9b49GcjJmdoxhBXNFIjiVJJVO5wul1auJLtSkuLvXch30VtKJ3bhwWEO/L7Jk0w6EbSBfVTIsAZhsVb0/cAuN39IF66HXccxjFBpGosLnCYaCM6CvRh5bt9gKUzWLIvPySA5elC+T0JnpJqqDMVoahizbaMQaZLeQM3w9BVn37NTIx41V4XVjiOe7ErmlcngEda1EU2xQPJzLFf4HsS5giYc5/FKcmhjsn4QJTkV+S0dmK6EdglLIMm0dMM4K4+Kl/TuJ9Y+KFm7aaouc/XfBX92prWJN5xd9hFfReXvVPG3bDPpYOljCRofNfkE60zDC0E2M1Gezkzx+ztrbMuV4yfNnd5bi1VEeumEnaexSgcR28X8AoUYRlrNxYzDfy+z/Oh8hEBHXoPiDEECot3KTCqWV3A8hT+4FkAr5XXcpePCpo74t3sLRhU+f22Lxpx21k25P1F/e+Og7rZbjs5rYLzKQsFt/Y7FUwJM0mN0H9kj8HTo6qvPG0NNUgNOVijF55VU9VX7HchTPh9MtiYbp5y46vQfE46y4sb3MeCUzR1hyPDwN/n4kPlIYURh742+z6CAfhF5yAE8RWZXGM6rEzRoNp5v/+kVaA+WAbGMLCp//kATTZdDmFVMdD+3kO+xdD/UKOHkX1GZVtKLvLkKgEUsw6WK2nWgOi5qaE=
  template:
    metadata:
      name: postgres-oms
      namespace: hello-svc
