---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis
  namespace: hello-svc
spec:
  encryptedData:
    REDIS_URL: AgDEWgCbEsfKiqtX/kDlqb5Fi5U76pJ/QT08P2hY04vd4mHbDN1/SIh8DvKZJlPNeigVIa2/zj5db6CFfXFwUKecyDUPr44Wr4C42zt6ql/py7IZ7PB2Ji0Yj8TS5tau+YLnlvkpZHi9ZmIMBthY4fFfq9eIfVofmwwgbjBFWgpF0aUTt0xD0G3FBAI0HreyJk+VexVAWFfT3cWiNWoCNc7EJaSDVxS07DjepfIHpJzf7PIhjmHxT9EcNOj/Mf/RdhCcCplL9P1XJt0ij0KvqKLwjkn9rYiS1N6GqgQ4/+GaNcGh8M35EWhSexVGxpg2tCZn+Axs2d4mW9PBzTQsk6btQ5YJutSEPrNSZeqPajZ8OY3o82KenSv1AIOUXGZRufE5Lo79HPcvsloPwgGEXbE/YC66c1kk3KY4ADftTW8r2Dysujs2cc/71TKA03i43nopErXe+3UuVTDmZTG2vl33owyQG2UUY6YYNJZHYK7V05sPV+6dyiYHflZKkbmALncgnIEDmpNUbWSqavSom/I5wapA5K/f267xtHWLQHrrlpnsB1JgBTF4wHXKshsI+EeXTnU40TQZrRxRlFa3j1kuVx74NDgXIh72hziaxhONwFyIzkKuGm4acMXDVXI2DNRX0HFWhRU4/el7Nxg9gYlP20PsdTPX/i2GnBxEf46XB7fPvN3JInKx0ogsV+5Py1pCTwBevCSeP9m/laacKtVHeRmITBiVtcn1IgS9qJwSYPaQ7Bgen2TaZr1Iy1o4K5Myt9OLIzG8ULarPzwPWI/aiiDcIVnUZNLLkEiozAPnt1RD9+uCJhuJmZPL7OwS4wzMN+loYHkiBk1n9WLRQg==
  template:
    metadata:
      name: redis
      namespace: hello-svc
