---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-reporting
  namespace: default
spec:
  encryptedData:
    DATABASE_URL: AgDfYkRkPdwZBUODNQlIKTkxrTxPg8mkI7jdwnUSxotVn7AeV++Qfp+Cm2lDIXYbE3BhR4aiewBnk9xoxPQL5lwGst3hWe4sMCZ78nmYhSUxKrie3ejCde7+XAUr0IOzDcXpfUgDFcmLzFxa0GIjbYKboNLGqdznpZ7ZorDdtoKn7de7wp+DhDYwwfSqbVsW+W4+FhjX6gBQDc4Agb0RZfcpkwfWLWfaB46mwOy6flzywhh7An5gOuhPjv8hlcPECfgfBCxoVXRLTVkwIErjD+h741BILUoYAkL2bAkfqOObv1f6JsgDGUZGRfKnQTiavrxi3iwETQxl9lU8VBIUqsaJMjeeTeaR5AVm9jlcG+5ycRDNvFof79y9oK3a2KCHtMWw7fSzAazBp6PLQ3sKSs9ioHup4NmBMXLt0E4D7sqHoxtfigULrEixAfdZLy/+A40Su4NblyneZ3bzgduihfbYJ/RMRTXvhQ9RGY/v1d7ajlt/AzesbYWFi9Bsx9aeYXhuV+KCcj1TH/iu3fP3qg8yYa+75EHhZl+EseJ+DhLc2/ewLSAAcZ2BSERLtML/k4sKyEv7/2ujT6McAXU9Q+Ys683AssANudccZ0bXhkX+bq0U2/M1CczJXyNqvCHl88gbE5Ir4ltzshpo9QBwTSDiDJOOyPeDmp7nkJvo5kGmTY9cRIerE0wIeGldB6AfylwNPgpOTddMxe9rJ7iFz4O9YoFEp19OJaDuAYx2qOVoFyB49VQuc7BBhXZfIiLHFi0fwoPHCz5Vd3hdwwlEZRuG+BfnYch6H7l4G5dgzC1EkjwsbK4FGZvo59nLNIlY3On6cQGQYeGGtxWDfv5jt0KOemCpPWri7NzSvNjTRoeL7itJzJZehH5Fb7OwlGUjEbUFcseTOVNVLMU=
  template:
    metadata:
      name: postgres-reporting
      namespace: default
