---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-pms
  namespace: default
spec:
  encryptedData:
    DATABASE_URL: AgCa7j89oyNZM6bbOiz667Jg2JlnTKwqZdofoBhTvGmq/jiz9JgQtJStyHxDZICZqILPgcoFirnh7swDsmHMYyUyM2F5xhjs79Ax+evGBdGrtpY2uvPT4s8U+m+0GFTiSbYYRMTOTNl0c+haMPK6UY4Q0bhhbekLk3ek8V59DdSBgoShflmPfNcUWYRKG2WBnt9Sr7B1S37EhoZsPXjcVLY6QfU7e2CTmZdiU6E+rVkg+/r/o20LPV7QLtRV8m39tQ9GtNS+ItpbgpYDs7Q1rIPNjrPi/Teha1SQs70Q6hv2v7AHcQpApJtToSIOpQFHVbXpvrk00Dt8wOaIxrUV55vIbGBoCV9wCUrH38likYXkQaUFv3lzfvbZiAWVcJxrYAzt546+Gej94QOKVMBXAra8SzAbr8A4JEFo1Gc/zZoR5gDRGR9v61wbAGzEdAh4ZmOrGF2gpeT8Z59tgn1xa4k3UD9WOERKZAj1AmyB5ltGxNSK5T1rw9qhgD6qKZwrQPocoW4T9GwiOPgjHUhoQHOMP5BIz7i8iM6NeToHrapqVEI4ku5k5Fw5hEPZqIeFR6ohotoot23/Xv6gxx8/VDp3sAbNqA3X4ug2tv+A8uQoGLboPr4iE8gCMZBbDfQ859w199/l1pQzM0ZPVSqMOyaYiU3a+OhFFK2lyT40TwRXFP6BrCDTHWKrkYLFo2+uEHMLGWX5vaCmg2rhYPBSu24hG9eRBOpYUsb/W5Hnn7sBY0KkrEBaSm2xb0QPVdQkGVjjh/fv52HH6+qxFOFSOi/g4ZQiD/L8ibF9r3d4yMGPhIQMGmDPYgjP9SilzK/wcr8P6QDr6nb1Rhb9R2QvIUygz/3MOQd1TzwhaLEZtcILqdx8BfqxnK0lhQFkbM8=
  template:
    metadata:
      name: postgres-pms
      namespace: default
