---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-oms
  namespace: default
spec:
  encryptedData:
    DATABASE_URL: AgBNUn7g+67mBLUI6U1GAJoAqNl+PPcus5THCuBP4vJ2/OJM71HsxaVdk4qBqlE052gq0mdv6T59jsf875hWuyxcVTdaXbaq42NmrhnUNZ/5bWDWBKfZly2J87GLiZFy5eSfQ7wZwXa7HCLQ9CBIDHag7HcbLab/sKejwgkuMxU7COG6fXo31e1P8UpxhvbtRyAc7ETDM9QQT1OXYV4rNsXX6QlfPUDtJ0zJR6Z0qGl+uBcAXCYqNXDu1ZMzrBMUGv7IeDjsw9u2YxtIdC46Yhy2HgJtfHJtBP6bXkeOURSS8a9AvLeLKBvmddLYQ8UHISTAVggBsJajKx3FmtdEpC+RYbB4kshbDgs2iKjOsjvBlBwwlIGOSLki+sL8fVLc/+xlV6r+asBdt8dA1LoA1/fKivQOw+910VKSXgC2xVYlpj/3HugLMS8pkaRcDsBcprY8lajJKIGs30Ac1jTHynpLsrC1yi/ecMyMaqAPJAwyTzofx++ZZVJ0XMioTpbPsm5BRJXz9mJU/z2yCTWXb/JRUPTy8iyscq4s9urnTdRLWolbBGKc6oEb65P/3gof7tF5IVXC6kncDEaju+dq1hsp2xxlf/yvRnAnOUpLFdqtazGL1NBFYT0+EL3BrZXBsasU/A7ead3FqptCga+1RIgZ91haku5fjU0zJ2xU/iXUadIioDaRBuHi04UHX66rWOpdrFHcyuRTOAGXbjoFDjoQ/T0G89lveyYB8u97aRDxH/KWokYuWok5fUdUIH1LW8lpRz6HrFy+GxExC+6MjTP/aifsH8spSeuZbMQgAO3RCCF8MPs6CF4dB/IcCZFgAOZI8fi2IqNt5gFUYb8MeFBbplSY3qxPwaG6//KTOq+H3Z1XM43V2wMN0x0ugLc=
  template:
    metadata:
      name: postgres-oms
      namespace: default
