---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis
  namespace: default
spec:
  encryptedData:
    REDIS_URL: AgBJgH3cRcNOTcksT7l6VeztmDZMe+KKkGWqSWeE5vf3lm8PsrImzmviPlafxyTzN6xZHh94o8cg3frhZymYF41HpiXt3mzPUnhu6loIrch3UzgCcFnj5P5L/vDc81HVaxn+m38oLlGVvCRJxx0nACXNcka99Y9yRMHZ7R5EqxqD7PB7iVGgel6FUmqdDyUxgDWFSVLMYaF+WcqA/NjBbdovmsKytoqrew9PEYJVAlg5G1XTDa3H2CQBcKWKZyJDw1ymqOSi/T7P9knskdnGAS6V7HtE/F414s0iV672cS/OoV7JrWaeZYUAkeEqMUM6h5lUUCouoP4cPxkLHHV/nC2mj+XiZIL4RLTC7WKP66oMwFypTYDXeoSBed7uM9QuywjyB9EEnJnQxQi/ZwZXNFmSDz1zujV5TOyhVeZnxnscSIVFX1mEAZokZxst5VFLMVFQ5rjPLZTRZ4XBps9q4ugswswyXn8XjBWcRDYcn7auWKEm8pFmcYxPCTy9vPhAcEkBnlptd1gYoeHUFAhKSzJdEOWkvbBFx7Md6mgetta85YLMP5MjJJvMJs8GQdpJZ5+QtkzlR3qNX4rftzapRm5WiQXiGoONnUqshVxKbx3XvqP52fcGjLsQnwfEdsOZHK/EwNvnWK0ZOrW9Qj1zGNyStc9plX7vrmamFaNnjjff1BlZ94sYWvg4Cyo4w0s0y79kGFwDsYJ7CFFHXZfBBOeORosgJeBcy78VWU+P42Aerz9v/nvaDtlTWUDdCWOQcQ7hHixaG4NjhONAKXwgHE/j0QI7lfwl6XLukl+OBPhX5DTo+RJj08DkF00TqeBqcdrhZUagtuhyYYAgDDxAxg==
  template:
    metadata:
      name: redis
      namespace: default
